
{{- define "common.template.deployment" -}}
{{ $ := (index . 0) }}
{{ $name := (index . 1) }}
{{ $current := (index . 2) }}
{{ $base := (index . 3) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ if $current.replicas }} {{ $current.replicas }} {{ else }} {{ $base.replicas }} {{ end }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - image: '{{ $current.image.repository }}'
          name: {{ $name }}
          ports:
            - containerPort: 80
{{ end }}

---
{{- define "common.template.service" -}}
{{ $ := (index . 0) }}
{{ $name := (index . 1) }}
{{ $current := (index . 2) }}
{{ $base := (index . 3) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32060
  type: NodePort
  selector:
    app: {{ $name }}

  {{ end }}